language: python
python:
  - "3.4"
# command to install dependencies
install:
 - "pip install gitpython"
 - "pip install cherrypy"
 - "pip install Jinja2"
 - "pip install -U numpy scipy scikit-learn"
# command to run tests
script: nosetests
